import type { TavoPlugin } from "@tavojs/core/plugin";

export type SitemapChangeFrequency =
  | "always"
  | "hourly"
  | "daily"
  | "weekly"
  | "monthly"
  | "yearly"
  | "never";

export type SitemapEntry = {
  /** A site-relative path or an absolute URL on siteUrl's origin. */
  path: string;
  alternates?: Readonly<Record<string, string>>;
  changeFrequency?: SitemapChangeFrequency;
  lastModified?: Date | string;
  priority?: number;
  /** Adds or removes a trailing slash from this entry and its alternate URLs. */
  trailingSlash?: boolean;
};

export type SitemapEntryInput = string | SitemapEntry;

export type SitemapSourceContext = {
  mode: "build" | "request";
  request?: Request;
};

export type SitemapEntryCollection =
  | Iterable<SitemapEntryInput>
  | AsyncIterable<SitemapEntryInput>;

export type SitemapEntrySource =
  | readonly SitemapEntryInput[]
  | ((context: SitemapSourceContext) =>
      | SitemapEntryCollection
      | Promise<SitemapEntryCollection>);

export type SitemapAutoDiscoverOptions = {
  /** Route paths or regular expressions to exclude. A string ending in /* excludes a subtree. */
  exclude?: readonly (string | RegExp)[];
  /** Overrides Tavo.js's configured pagesDir. Normally detected automatically. */
  pagesDir?: string;
  /** Adds or removes trailing slashes from discovered page routes. */
  trailingSlash?: boolean;
};

export type RobotsRule = {
  userAgent: string | readonly string[];
  allow?: string | readonly string[];
  crawlDelay?: number;
  disallow?: string | readonly string[];
};

export type RobotsOptions = {
  /** Additional absolute sitemap URLs to advertise. */
  additionalSitemaps?: readonly string[];
  cacheControl?: false | string;
  host?: string;
  /** Include the sitemap generated by this plugin. Defaults to true. */
  includeSitemap?: boolean;
  path?: string;
  rules?: readonly RobotsRule[];
};

export type CreateSitemapPluginOptions = {
  /** Automatically discover concrete Tavo.js file routes. Defaults to true. */
  autoDiscover?: boolean | SitemapAutoDiscoverOptions;
  cacheControl?: false | string;
  /**
   * Emit sitemap assets during the client build. Defaults to true for entry
   * arrays and false for request-time entry callbacks.
   */
  emitStatic?: boolean;
  /** Extra entries or overrides for automatically discovered routes. */
  entries?: SitemapEntrySource;
  /** Maximum generated XML bytes. Cannot exceed the sitemap protocol limit. */
  maxBytes?: number;
  /** Maximum URL entries. Cannot exceed the sitemap protocol limit. */
  maxEntries?: number;
  path?: string;
  robots?: true | RobotsOptions;
  /** Absolute HTTP(S) origin, for example https://example.com. */
  siteUrl: string;
};

export type SitemapRuntime = {
  readonly robotsPath?: string;
  readonly sitemapPath: string;
  discoveredPaths(): readonly string[];
  renderRobots(): string | null;
  renderSitemap(context?: SitemapSourceContext): Promise<string>;
};

export type SitemapPlugin = TavoPlugin & {
  sitemap: SitemapRuntime;
};
